# Source: cluster-api-aws/templates/aws-machinetemplates-control-plane.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachineTemplate
metadata:
  name: 8e18c5b6-ebce-440b-8c08-c1f7d11683d4-control-plane
  namespace: 8e18c5b6-ebce-440b-8c08-c1f7d11683d4
spec:
  template:
    spec:
      iamInstanceProfile: control-plane.cluster-api-provider-aws.sigs.k8s.io
      instanceType: t3.medium
      sshKeyName: tks-seoul
      rootVolume:
        size: 20
        type: gp2
