# Source: cluster-api-aws/templates/job-check.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: 8e18c5b6-ebce-440b-8c08-c1f7d11683d4-capi-aws-check
  namespace: 8e18c5b6-ebce-440b-8c08-c1f7d11683d4
spec:
  template:
    metadata:
      name: 8e18c5b6-ebce-440b-8c08-c1f7d11683d4-capi-aws
    spec:
      serviceAccountName: 8e18c5b6-ebce-440b-8c08-c1f7d11683d4-capi-aws
      containers:
      - name: wait-for-ready
        image: "ghcr.io/openinfradev/python_kubectl_argo:v1.1.0"
        imagePullPolicy: IfNotPresent
        command:
        - timeout 
        - 5m
        - /wait_for_kubeconfig.sh  
        - 8e18c5b6-ebce-440b-8c08-c1f7d11683d4
        - 8e18c5b6-ebce-440b-8c08-c1f7d11683d4
        volumeMounts:
        - name: vol
          subPath: wait_for_kubeconfig.sh
          mountPath: /wait_for_kubeconfig.sh
      volumes:
      - name: vol
        configMap:
          name: 8e18c5b6-ebce-440b-8c08-c1f7d11683d4-capi-aws
          defaultMode: 0555
      restartPolicy: OnFailure
