---
# Source: cluster-autoscaler/templates/rbac-for-mgmt-cluster-access.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-autoscaler
  namespace: 8e18c5b6-ebce-440b-8c08-c1f7d11683d4
